trigger:
  - main

pool:
  name: 'selhostedravi'
  demands:
    - agent.name -equals selhostedagent

parameters:
- name: ciParametersFile
  default: 'devops-project-ci-parameters.yml'
  type: string

steps:
# Script to set up Java 20.0.2 manually (if not already installed)
- script: |
    echo "Setting up Java 20.0.2"
    wget https://download.java.net/java/GA/jdk20/2/GPL/openjdk-20.0.2_linux-x64_bin.tar.gz
    tar xzf openjdk-20.0.2_linux-x64_bin.tar.gz
    sudo mv jdk-20.0.2 /usr/local/
    echo "##vso[task.prependpath]/usr/local/jdk-20.0.2/bin"
    java -version
  displayName: 'Set up Java 20.0.2'

# Script to set up Maven 3.9.6 manually (if not already installed)
- script: |
    echo "Setting up Maven 3.9.6"
    wget https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
    tar xzf apache-maven-3.9.6-bin.tar.gz
    sudo mv apache-maven-3.9.6 /usr/local/
    echo "##vso[task.prependpath]/usr/local/apache-maven-3.9.6/bin"
    mvn -version
  displayName: 'Set up Maven 3.9.6'

# Clean the project
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/local/apache-maven-3.9.6'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    jdkSourceOption: 'JDKVersion'
  displayName: 'Maven clean'

# Run unit tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/local/apache-maven-3.9.6'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    jdkSourceOption: 'JDKVersion'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Run Unit Tests'

# Run integration tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/local/apache-maven-3.9.6'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    jdkSourceOption: 'JDKVersion'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Run Integration Tests'

# Package the application, skipping tests as they have already been run
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/local/apache-maven-3.9.6'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    jdkSourceOption: 'JDKVersion'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Maven package'

# Copy files to the staging directory
- task: CopyFiles@2
  inputs:
    contents: '**/target/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Publish the build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'
