trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: ciParametersFile
  default: 'devops-project-ci-parameters.yml'
  type: string

steps:
# Step to set up Java 20 using JavaToolInstaller
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '20.0.2'
    jdkArchitectureOption: 'x64'
  displayName: 'Set up Java 20.0.2'

# Step to clean the project
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/share/maven'
  displayName: 'Maven clean'

# Step to run unit tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/share/maven'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Run Unit Tests'

# Step to run integration tests
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'verify'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/share/maven'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Run Integration Tests'

# Step to package the application, skipping tests as they have already been run
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'
    mavenVersionOption: 'Custom'
    mavenDirectory: '/usr/share/maven'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '20.0.2'
    mavenAuthenticateFeed: true
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Maven package'

# Step to copy files to the staging directory
- task: CopyFiles@2
  inputs:
    contents: '**/target/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy files to staging directory'

# Step to publish the build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: drop'
