resources:
  pipelines:
  - pipeline: ciPipeline
    source: rpnitdgp.devops-project-ci-pipeline
    trigger:
      branches:
        include:
          - master

trigger: none

pool:
  name: 'selhostedravi'
  demands:
    - agent.name -equals selhostedagent

parameters:
- name: releaseParametersFile
  default: 'devops-project-release-parameters.yml'
  type: string

variables:
- name: azureProjConnection
  value: 'testSubsSchipholProject' 
- name: devLocation
  value: 'West Europe'
- name: appServicePlanName
  value : 'schipholAppServicePlan'
- name: appInsightsName
  value : 'schipholInsights'
- name: appName
  value: 'schipholAppNew'
- name: azureConnection
  value: 'testSubsSchipholProject'

stages:
- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  jobs:
  - deployment: DeployWebApp_Dev
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ciPipeline
            artifact: drop

          - script: |
              echo "Listing root directory:"
              dir "$(Pipeline.Workspace)"
            displayName: 'List root directory'

          - script: |
              echo "Listing _work directory:"
              dir "$(Pipeline.Workspace)\.."
            displayName: 'List _work directory'

          - script: |
              echo "Listing ciPipeline directory:"
              dir "$(Pipeline.Workspace)\ciPipeline"
            displayName: 'List ciPipeline directory'

          - script: |
              echo "Listing drop directory:"
              dir "$(Pipeline.Workspace)\ciPipeline\drop"
            displayName: 'List drop directory'

          - script: |
              echo "Listing recipeapp target directory:"
              dir "$(Pipeline.Workspace)\ciPipeline\drop\recipeapp\target"
            displayName: 'List recipeapp target directory'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: ${{ variables.azureProjConnection }}
              subscriptionId: ${{ parameters.releaseParametersFile.subscriptionId }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: ${{ parameters.releaseParametersFile.devResourceGroupName }}
              location: ${{ variables.devLocation }}
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/ciPipeline/drop/azure-deploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/ciPipeline/drop/azure-deploy.parameters.json'
              overrideParameters: '-appName "$(appName)" -appServicePlanName "$(appServicePlanName)" -appInsightsName "$(appInsightsName)"'
              deploymentMode: 'Incremental'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureConnection)
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/ciPipeline/drop/*.jar'
              appType: 'javaContainer'

- stage: Deploy_Prod
  displayName: 'Deploy to Prod'
  jobs:
  - deployment: DeployWebApp_Prod
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
            displayName: 'Download Artifacts'

          - script: |
              echo "Listing root directory:"
              dir "$(Pipeline.Workspace)"
            displayName: 'List root directory'

          - script: |
              echo "Listing _work directory:"
              dir "$(Pipeline.Workspace)\.."
            displayName: 'List _work directory'

          - script: |
              echo "Listing ciPipeline directory:"
              dir "$(Pipeline.Workspace)\ciPipeline"
            displayName: 'List ciPipeline directory'

          - script: |
              echo "Listing drop directory:"
              dir "$(Pipeline.Workspace)\ciPipeline\drop"
            displayName: 'List drop directory'

          - script: |
              echo "Listing recipeapp target directory:"
              dir "$(Pipeline.Workspace)\ciPipeline\drop\recipeapp\target"
            displayName: 'List recipeapp target directory'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: ${{ variables.azureProjConnection }}
              subscriptionId: ${{ parameters.releaseParametersFile.subscriptionId }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: ${{ parameters.releaseParametersFile.devResourceGroupName }}
              location: ${{ variables.devLocation }}
              templateLocation: 'Linked artifact'
              csmFile: '$(System.DefaultWorkingDirectory)/drop/azure-deploy.json'
              csmParametersFile: '$(System.DefaultWorkingDirectory)/drop/azure-deploy.parameters.json'
              overrideParameters: '-appName "$(appName)" -appServicePlanName "$(appServicePlanName)" -appInsightsName "$(appInsightsName)"'
              deploymentMode: 'Incremental'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureConnection)
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/ciPipeline/drop/*.jar'
              appType: 'javaContainer'
