resources:
  pipelines:
  - pipeline: ciPipeline
    source: rpnitdgp.devops-project-ci-pipeline
    trigger:
      branches:
        include:
          - master

trigger: none

pool:
  name: 'selhostedravi'
  demands:
    - agent.name -equals selhostedagent

parameters:
- name: releaseParametersFile
  default: 'devops-project-release-parameters.yml'
  type: string

variables:
- name: azureProjConnection
  value: 'testSubsSchipholProject' 
- name: devLocation
  value: 'West Europe'

stages:
- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  jobs:
  - deployment: DeployWebApp_Dev
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ciPipeline
            artifact: drop

          - script: |
              echo "Listing downloaded files:"
              ls -R $(Pipeline.Workspace)/drop
            displayName: 'List downloaded files'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: ${{ variables.azureProjConnection }}
              subscriptionId: ${{ parameters.releaseParametersFile.subscriptionId }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: ${{ parameters.releaseParametersFile.devResourceGroupName }}
              location: ${{ variables.devLocation }}
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/devops-project/templates/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/drop/devops-project/templates/azuredeploy.parameters.json'
              overrideParameters: '-appName "$(appName)" -appServicePlanName "$(appServicePlanName)" -appInsightsName "$(appInsightsName)"'
              deploymentMode: 'Incremental'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: ${{ parameters.releaseParametersFile.azureConnection }}
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/drop/recipeapp/target/recipeapp-0.0.1-SNAPSHOT.war'
              appType: 'webApp'

- stage: Deploy_Prod
  displayName: 'Deploy to Prod'
  jobs:
  - deployment: DeployWebApp_Prod
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: ciPipeline
            artifact: drop

          - script: |
              echo "Listing downloaded files:"
              ls -R $(Pipeline.Workspace)/drop
            displayName: 'List downloaded files'

          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: ${{ variables.azureProjConnection }}
              subscriptionId: ${{ parameters.releaseParametersFile.subscriptionId }}
              action: 'Create Or Update Resource Group'
              resourceGroupName: ${{ parameters.releaseParametersFile.prodResourceGroupName }}
              location: ${{ variables.devLocation }}
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/devops-project/templates/azuredeploy.json'
              csmParametersFile: '$(Pipeline.Workspace)/drop/devops-project/templates/azuredeploy.parameters.json'
              overrideParameters: '-appName "$(appName)" -appServicePlanName "$(appServicePlanName)" -appInsightsName "$(appInsightsName)"'
              deploymentMode: 'Incremental'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: ${{ parameters.releaseParametersFile.azureConnection }}
              appName: '$(appName)'
              package: '$(Pipeline.Workspace)/drop/recipeapp/target/recipeapp-0.0.1-SNAPSHOT.war'
              appType: 'webApp'
